### ISSUE TITLE
Include images from imgur to the repository

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/getting-things-gnome.github.io#7]
There are links to images on Imgur (Such as in the old design page, and some for google summer of code pages). They still work, but we may want to copy them to the repo so they move "with them".

Also we could use some (lossless) PNG optimizer before inserting them here in this repo so we have the smallest image files for them so they don't take up too much space.

**Comment by nekohayo** [comment]
While it is excruciatingly slow, I have found [Yoga](https://yoga.flozz.org/) to be the most practical batch PNG optimizer app. Ideally, if you want to squeeze an extra 10% more stackable with the optimization, you want to make sure to remove the alpha channel from images (if they don't actually use transparency) using GIMP before encoding with Yoga.
